# Generated by Django 3.1.7 on 2021-04-29 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=300)),
                ('Reason', models.TextField()),
                ('Request_time', models.DateTimeField(auto_now_add=True)),
                ('Request_Status', models.CharField(choices=[('progressing', 'progressing'), ('accept', 'ACCEPT'), ('reject', 'REJECT')], default='progressing', max_length=100)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee_details')),
            ],
            options={
                'verbose_name_plural': 'Leave Requests',
            },
        ),
    ]
