# Generated by Django 3.1.7 on 2021-04-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_leave_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='Request_Status',
            field=models.CharField(choices=[('progressing', 'Progressing'), ('accept', 'ACCEPT'), ('reject', 'REJECT')], default='progressing', max_length=100),
        ),
    ]
