# Generated by Django 3.1.7 on 2021-04-29 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210429_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='Request_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 12, 51, 16, 968958)),
        ),
    ]
