# Generated by Django 3.1.7 on 2021-04-29 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210429_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='Request_Status',
            field=models.CharField(choices=[('Progressing', 'Progressing'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Progressing', max_length=100),
        ),
        migrations.AlterField(
            model_name='leave_request',
            name='Request_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 21, 24, 9, 463438)),
        ),
    ]
