# Generated by Django 4.1.12 on 2023-10-15 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210429_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='Request_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 7, 1, 35, 316932)),
        ),
    ]
