# Generated by Django 4.1.12 on 2023-10-15 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_leave_request_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='Request_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 9, 26, 51, 519328)),
        ),
    ]
